# Generated by Django 6.0.5 on 2026-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('normalized_unit', models.CharField(default='kgCO2e', max_length=20)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('original_row_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
